FROM alpine:3.14

ARG BOR_DIR=/var/lib/bor
ENV BOR_DIR=$BOR_DIR

RUN apk add --no-cache ca-certificates && \
    mkdir -p ${BOR_DIR}

WORKDIR ${BOR_DIR}
COPY bor /usr/bin/
COPY builder/files/genesis-shibarium.json ${BOR_DIR}
COPY builder/files/genesis-puppynet.json ${BOR_DIR}

EXPOSE 8545 8546 8547 30303 30303/udp
ENTRYPOINT ["bor"]
