// Code generated by protoc-gen-go. DO NOT EDIT.
// source: command/server/proto/server.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PprofRequest_Type int32

const (
	PprofRequest_LOOKUP PprofRequest_Type = 0
	PprofRequest_CPU    PprofRequest_Type = 1
	PprofRequest_TRACE  PprofRequest_Type = 2
)

var PprofRequest_Type_name = map[int32]string{
	0: "LOOKUP",
	1: "CPU",
	2: "TRACE",
}

var PprofRequest_Type_value = map[string]int32{
	"LOOKUP": 0,
	"CPU":    1,
	"TRACE":  2,
}

func (x PprofRequest_Type) String() string {
	return proto.EnumName(PprofRequest_Type_name, int32(x))
}

func (PprofRequest_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e4c7afeb3932d722, []int{9, 0}
}

type PeersAddRequest struct {
	Enode                string   `protobuf:"bytes,1,opt,name=enode,proto3" json:"enode,omitempty"`
	Trusted              bool     `protobuf:"varint,2,opt,name=trusted,proto3" json:"trusted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeersAddRequest) Reset()         { *m = PeersAddRequest{} }
func (m *PeersAddRequest) String() string { return proto.CompactTextString(m) }
func (*PeersAddRequest) ProtoMessage()    {}
func (*PeersAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4c7afeb3932d722, []int{0}
}

func (m *PeersAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeersAddRequest.Unmarshal(m, b)
}
func (m *PeersAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeersAddRequest.Marshal(b, m, deterministic)
}
func (m *PeersAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeersAddRequest.Merge(m, src)
}
func (m *PeersAddRequest) XXX_Size() int {
	return xxx_messageInfo_PeersAddRequest.Size(m)
}
func (m *PeersAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeersAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeersAddRequest proto.InternalMessageInfo

func (m *PeersAddRequest) GetEnode() string {
	if m != nil {
		return m.Enode
	}
	return ""
}

func (m *PeersAddRequest) GetTrusted() bool {
	if m != nil {
		return m.Trusted
	}
	return false
}

type PeersAddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeersAddResponse) Reset()         { *m = PeersAddResponse{} }
func (m *PeersAddResponse) String() string { return proto.CompactTextString(m) }
func (*PeersAddResponse) ProtoMessage()    {}
func (*PeersAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4c7afeb3932d722, []int{1}
}

func (m *PeersAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeersAddResponse.Unmarshal(m, b)
}
func (m *PeersAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeersAddResponse.Marshal(b, m, deterministic)
}
func (m *PeersAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeersAddResponse.Merge(m, src)
}
func (m *PeersAddResponse) XXX_Size() int {
	return xxx_messageInfo_PeersAddResponse.Size(m)
}
func (m *PeersAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PeersAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PeersAddResponse proto.InternalMessageInfo

type PeersRemoveRequest struct {
	Enode                string   `protobuf:"bytes,1,opt,name=enode,proto3" json:"enode,omitempty"`
	Trusted              bool     `protobuf:"varint,2,opt,name=trusted,proto3" json:"trusted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeersRemoveRequest) Reset()         { *m = PeersRemoveRequest{} }
func (m *PeersRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*PeersRemoveRequest) ProtoMessage()    {}
func (*PeersRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4c7afeb3932d722, []int{2}
}

func (m *PeersRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeersRemoveRequest.Unmarshal(m, b)
}
func (m *PeersRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeersRemoveRequest.Marshal(b, m, deterministic)
}
func (m *PeersRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeersRemoveRequest.Merge(m, src)
}
func (m *PeersRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_PeersRemoveRequest.Size(m)
}
func (m *PeersRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeersRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeersRemoveRequest proto.InternalMessageInfo

func (m *PeersRemoveRequest) GetEnode() string {
	if m != nil {
		return m.Enode
	}
	return ""
}

func (m *PeersRemoveRequest) GetTrusted() bool {
	if m != nil {
		return m.Trusted
	}
	return false
}

type PeersRemoveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeersRemoveResponse) Reset()         { *m = PeersRemoveResponse{} }
func (m *PeersRemoveResponse) String() string { return proto.CompactTextString(m) }
func (*PeersRemoveResponse) ProtoMessage()    {}
func (*PeersRemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4c7afeb3932d722, []int{3}
}

func (m *PeersRemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeersRemoveResponse.Unmarshal(m, b)
}
func (m *PeersRemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeersRemoveResponse.Marshal(b, m, deterministic)
}
func (m *PeersRemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeersRemoveResponse.Merge(m, src)
}
func (m *PeersRemoveResponse) XXX_Size() int {
	return xxx_messageInfo_PeersRemoveResponse.Size(m)
}
func (m *PeersRemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PeersRemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PeersRemoveResponse proto.InternalMessageInfo

type PeersListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeersListRequest) Reset()         { *m = PeersListRequest{} }
func (m *PeersListRequest) String() string { return proto.CompactTextString(m) }
func (*PeersListRequest) ProtoMessage()    {}
func (*PeersListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4c7afeb3932d722, []int{4}
}

func (m *PeersListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeersListRequest.Unmarshal(m, b)
}
func (m *PeersListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeersListRequest.Marshal(b, m, deterministic)
}
func (m *PeersListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeersListRequest.Merge(m, src)
}
func (m *PeersListRequest) XXX_Size() int {
	return xxx_messageInfo_PeersListRequest.Size(m)
}
func (m *PeersListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeersListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeersListRequest proto.InternalMessageInfo

type PeersListResponse struct {
	Peers                []*Peer  `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeersListResponse) Reset()         { *m = PeersListResponse{} }
func (m *PeersListResponse) String() string { return proto.CompactTextString(m) }
func (*PeersListResponse) ProtoMessage()    {}
func (*PeersListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4c7afeb3932d722, []int{5}
}

func (m *PeersListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeersListResponse.Unmarshal(m, b)
}
func (m *PeersListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeersListResponse.Marshal(b, m, deterministic)
}
func (m *PeersListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeersListResponse.Merge(m, src)
}
func (m *PeersListResponse) XXX_Size() int {
	return xxx_messageInfo_PeersListResponse.Size(m)
}
func (m *PeersListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PeersListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PeersListResponse proto.InternalMessageInfo

func (m *PeersListResponse) GetPeers() []*Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type PeersStatusRequest struct {
	Enode                string   `protobuf:"bytes,1,opt,name=enode,proto3" json:"enode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeersStatusRequest) Reset()         { *m = PeersStatusRequest{} }
func (m *PeersStatusRequest) String() string { return proto.CompactTextString(m) }
func (*PeersStatusRequest) ProtoMessage()    {}
func (*PeersStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4c7afeb3932d722, []int{6}
}

func (m *PeersStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeersStatusRequest.Unmarshal(m, b)
}
func (m *PeersStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeersStatusRequest.Marshal(b, m, deterministic)
}
func (m *PeersStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeersStatusRequest.Merge(m, src)
}
func (m *PeersStatusRequest) XXX_Size() int {
	return xxx_messageInfo_PeersStatusRequest.Size(m)
}
func (m *PeersStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeersStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeersStatusRequest proto.InternalMessageInfo

func (m *PeersStatusRequest) GetEnode() string {
	if m != nil {
		return m.Enode
	}
	return ""
}

type PeersStatusResponse struct {
	Peer                 *Peer    `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeersStatusResponse) Reset()         { *m = PeersStatusResponse{} }
func (m *PeersStatusResponse) String() string { return proto.CompactTextString(m) }
func (*PeersStatusResponse) ProtoMessage()    {}
func (*PeersStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4c7afeb3932d722, []int{7}
}

func (m *PeersStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeersStatusResponse.Unmarshal(m, b)
}
func (m *PeersStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeersStatusResponse.Marshal(b, m, deterministic)
}
func (m *PeersStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeersStatusResponse.Merge(m, src)
}
func (m *PeersStatusResponse) XXX_Size() int {
	return xxx_messageInfo_PeersStatusResponse.Size(m)
}
func (m *PeersStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PeersStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PeersStatusResponse proto.InternalMessageInfo

func (m *PeersStatusResponse) GetPeer() *Peer {
	if m != nil {
		return m.Peer
	}
	return nil
}

type Peer struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Enode                string   `protobuf:"bytes,2,opt,name=enode,proto3" json:"enode,omitempty"`
	Enr                  string   `protobuf:"bytes,3,opt,name=enr,proto3" json:"enr,omitempty"`
	Caps                 []string `protobuf:"bytes,4,rep,name=caps,proto3" json:"caps,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Trusted              bool     `protobuf:"varint,6,opt,name=trusted,proto3" json:"trusted,omitempty"`
	Static               bool     `protobuf:"varint,7,opt,name=static,proto3" json:"static,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Peer) Reset()         { *m = Peer{} }
func (m *Peer) String() string { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()    {}
func (*Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4c7afeb3932d722, []int{8}
}

func (m *Peer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Peer.Unmarshal(m, b)
}
func (m *Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Peer.Marshal(b, m, deterministic)
}
func (m *Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Peer.Merge(m, src)
}
func (m *Peer) XXX_Size() int {
	return xxx_messageInfo_Peer.Size(m)
}
func (m *Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_Peer proto.InternalMessageInfo

func (m *Peer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Peer) GetEnode() string {
	if m != nil {
		return m.Enode
	}
	return ""
}

func (m *Peer) GetEnr() string {
	if m != nil {
		return m.Enr
	}
	return ""
}

func (m *Peer) GetCaps() []string {
	if m != nil {
		return m.Caps
	}
	return nil
}

func (m *Peer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Peer) GetTrusted() bool {
	if m != nil {
		return m.Trusted
	}
	return false
}

func (m *Peer) GetStatic() bool {
	if m != nil {
		return m.Static
	}
	return false
}

type PprofRequest struct {
	Type                 PprofRequest_Type `protobuf:"varint,1,opt,name=type,proto3,enum=proto.PprofRequest_Type" json:"type,omitempty"`
	Profile              string            `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Seconds              int64             `protobuf:"varint,3,opt,name=seconds,proto3" json:"seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PprofRequest) Reset()         { *m = PprofRequest{} }
func (m *PprofRequest) String() string { return proto.CompactTextString(m) }
func (*PprofRequest) ProtoMessage()    {}
func (*PprofRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4c7afeb3932d722, []int{9}
}

func (m *PprofRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PprofRequest.Unmarshal(m, b)
}
func (m *PprofRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PprofRequest.Marshal(b, m, deterministic)
}
func (m *PprofRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PprofRequest.Merge(m, src)
}
func (m *PprofRequest) XXX_Size() int {
	return xxx_messageInfo_PprofRequest.Size(m)
}
func (m *PprofRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PprofRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PprofRequest proto.InternalMessageInfo

func (m *PprofRequest) GetType() PprofRequest_Type {
	if m != nil {
		return m.Type
	}
	return PprofRequest_LOOKUP
}

func (m *PprofRequest) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *PprofRequest) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

type PprofResponse struct {
	Payload              string            `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers              map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PprofResponse) Reset()         { *m = PprofResponse{} }
func (m *PprofResponse) String() string { return proto.CompactTextString(m) }
func (*PprofResponse) ProtoMessage()    {}
func (*PprofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4c7afeb3932d722, []int{10}
}

func (m *PprofResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PprofResponse.Unmarshal(m, b)
}
func (m *PprofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PprofResponse.Marshal(b, m, deterministic)
}
func (m *PprofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PprofResponse.Merge(m, src)
}
func (m *PprofResponse) XXX_Size() int {
	return xxx_messageInfo_PprofResponse.Size(m)
}
func (m *PprofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PprofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PprofResponse proto.InternalMessageInfo

func (m *PprofResponse) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *PprofResponse) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.PprofRequest_Type", PprofRequest_Type_name, PprofRequest_Type_value)
	proto.RegisterType((*PeersAddRequest)(nil), "proto.PeersAddRequest")
	proto.RegisterType((*PeersAddResponse)(nil), "proto.PeersAddResponse")
	proto.RegisterType((*PeersRemoveRequest)(nil), "proto.PeersRemoveRequest")
	proto.RegisterType((*PeersRemoveResponse)(nil), "proto.PeersRemoveResponse")
	proto.RegisterType((*PeersListRequest)(nil), "proto.PeersListRequest")
	proto.RegisterType((*PeersListResponse)(nil), "proto.PeersListResponse")
	proto.RegisterType((*PeersStatusRequest)(nil), "proto.PeersStatusRequest")
	proto.RegisterType((*PeersStatusResponse)(nil), "proto.PeersStatusResponse")
	proto.RegisterType((*Peer)(nil), "proto.Peer")
	proto.RegisterType((*PprofRequest)(nil), "proto.PprofRequest")
	proto.RegisterType((*PprofResponse)(nil), "proto.PprofResponse")
	proto.RegisterMapType((map[string]string)(nil), "proto.PprofResponse.HeadersEntry")
}

func init() { proto.RegisterFile("command/server/proto/server.proto", fileDescriptor_e4c7afeb3932d722) }

var fileDescriptor_e4c7afeb3932d722 = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6b, 0x1b, 0x3d,
	0x10, 0x7e, 0xf7, 0xcb, 0x8e, 0xc7, 0x79, 0x53, 0x77, 0xf2, 0xa5, 0xee, 0xa5, 0xf6, 0x1e, 0x8a,
	0x29, 0xc5, 0x06, 0x17, 0x42, 0x49, 0xa0, 0xe0, 0x7c, 0x40, 0xa1, 0x81, 0x18, 0x35, 0xb9, 0xf4,
	0xb6, 0xf5, 0xaa, 0xd4, 0xd4, 0x5e, 0x6d, 0x57, 0xb2, 0x61, 0xff, 0x49, 0xcf, 0xfd, 0x29, 0xfd,
	0x65, 0x45, 0x5a, 0x29, 0xd1, 0x26, 0xa6, 0x87, 0x9e, 0x56, 0xcf, 0xcc, 0xe8, 0x79, 0x66, 0x46,
	0x7e, 0x0c, 0x83, 0x39, 0x5f, 0xad, 0xd2, 0x3c, 0x1b, 0x0b, 0x56, 0x6e, 0x58, 0x39, 0x2e, 0x4a,
	0x2e, 0xb9, 0x01, 0x23, 0x0d, 0x30, 0xd2, 0x9f, 0x64, 0x0a, 0xcf, 0x66, 0x8c, 0x95, 0x62, 0x9a,
	0x65, 0x94, 0xfd, 0x58, 0x33, 0x21, 0xf1, 0x00, 0x22, 0x96, 0xf3, 0x8c, 0x11, 0xaf, 0xef, 0x0d,
	0x3b, 0xb4, 0x06, 0x48, 0xa0, 0x2d, 0xcb, 0xb5, 0x90, 0x2c, 0x23, 0x7e, 0xdf, 0x1b, 0xee, 0x50,
	0x0b, 0x13, 0x84, 0xde, 0x03, 0x85, 0x28, 0x78, 0x2e, 0x58, 0x72, 0x09, 0xa8, 0x63, 0x94, 0xad,
	0xf8, 0x86, 0xfd, 0x2b, 0xf3, 0x21, 0xec, 0x37, 0x58, 0x0c, 0xb9, 0x15, 0xbc, 0x5e, 0x08, 0x69,
	0xa8, 0x93, 0x13, 0x78, 0xee, 0xc4, 0xea, 0x42, 0x1c, 0x40, 0x54, 0xa8, 0x20, 0xf1, 0xfa, 0xc1,
	0xb0, 0x3b, 0xe9, 0xd6, 0xa3, 0x8f, 0x54, 0x21, 0xad, 0x33, 0xc9, 0x6b, 0xd3, 0xe8, 0x27, 0x99,
	0xca, 0xb5, 0xf8, 0x6b, 0xa3, 0xc9, 0x89, 0x69, 0xc7, 0xd6, 0x1a, 0x95, 0x97, 0x10, 0x2a, 0x2e,
	0x5d, 0xfb, 0x48, 0x44, 0x27, 0x92, 0x9f, 0x1e, 0x84, 0x0a, 0xe2, 0x1e, 0xf8, 0x8b, 0xcc, 0x70,
	0xfa, 0x8b, 0xec, 0x41, 0xc6, 0x77, 0xf7, 0xd1, 0x83, 0x80, 0xe5, 0x25, 0x09, 0x74, 0x4c, 0x1d,
	0x11, 0x21, 0x9c, 0xa7, 0x85, 0x20, 0x61, 0x3f, 0x18, 0x76, 0xa8, 0x3e, 0xab, 0x58, 0x9e, 0xae,
	0x18, 0x89, 0x74, 0x99, 0x3e, 0xbb, 0x9b, 0x6c, 0x35, 0x36, 0x89, 0x47, 0xd0, 0x12, 0x32, 0x95,
	0x8b, 0x39, 0x69, 0xeb, 0x84, 0x41, 0xaa, 0xb5, 0xdd, 0x59, 0x51, 0xf2, 0xaf, 0x76, 0xf2, 0x37,
	0x10, 0xca, 0xaa, 0xa8, 0x07, 0xdf, 0x9b, 0x10, 0x3b, 0x8c, 0x53, 0x32, 0xba, 0xad, 0x0a, 0x46,
	0x75, 0x95, 0x12, 0x54, 0x99, 0xc5, 0xd2, 0x8e, 0x60, 0xa1, 0xca, 0x08, 0x36, 0xe7, 0x79, 0x26,
	0xf4, 0x20, 0x01, 0xb5, 0x30, 0x79, 0x05, 0xa1, 0x62, 0x40, 0x80, 0xd6, 0xf5, 0xcd, 0xcd, 0xc7,
	0xbb, 0x59, 0xef, 0x3f, 0x6c, 0x43, 0x70, 0x31, 0xbb, 0xeb, 0x79, 0xd8, 0x81, 0xe8, 0x96, 0x4e,
	0x2f, 0xae, 0x7a, 0x7e, 0xf2, 0xcb, 0x83, 0xff, 0x8d, 0xae, 0x59, 0xb4, 0x52, 0x4b, 0xab, 0x25,
	0x4f, 0xed, 0x0e, 0x2d, 0xc4, 0x33, 0x68, 0x7f, 0x63, 0x69, 0xa6, 0x9e, 0xda, 0xd7, 0x4f, 0x3d,
	0x68, 0x36, 0x5e, 0x13, 0x8c, 0x3e, 0xd4, 0x35, 0x57, 0xb9, 0x2c, 0x2b, 0x6a, 0x6f, 0xc4, 0xa7,
	0xb0, 0xeb, 0x26, 0xd4, 0xfe, 0xbf, 0xb3, 0xca, 0x48, 0xa8, 0xa3, 0x7a, 0xa7, 0x4d, 0xba, 0x5c,
	0xdf, 0xbf, 0x93, 0x06, 0xa7, 0xfe, 0x3b, 0x6f, 0xf2, 0xdb, 0x87, 0xe0, 0x9c, 0x97, 0x38, 0x81,
	0x48, 0x4b, 0xe1, 0xfe, 0x96, 0x8d, 0xc5, 0x07, 0xdb, 0xba, 0xc1, 0x33, 0xd8, 0xb1, 0xbe, 0xc1,
	0x23, 0xe7, 0x57, 0xe3, 0x78, 0x31, 0x3e, 0x7e, 0x12, 0x37, 0x97, 0x2f, 0xa1, 0xeb, 0x58, 0x03,
	0x5f, 0xb8, 0x75, 0x0d, 0xd3, 0xc5, 0xf1, 0xb6, 0x94, 0x61, 0x79, 0x0f, 0x9d, 0x7b, 0xd7, 0x60,
	0x43, 0xcb, 0xf1, 0x56, 0x4c, 0x9e, 0x26, 0x1e, 0x75, 0x51, 0x3b, 0xa2, 0xd9, 0x45, 0xc3, 0x51,
	0xcd, 0x2e, 0x9a, 0x06, 0x3a, 0x3f, 0xfe, 0x7c, 0x38, 0xde, 0xf6, 0x87, 0xf5, 0xa5, 0xa5, 0x3f,
	0x6f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x64, 0x40, 0x80, 0xcf, 0x04, 0x00, 0x00,
}
