chain = "amoy"
datadir = "/var/lib/bor/data"
syncmode = "full"
snapshot = true
verbosity = 4

[p2p]
  bind = "0.0.0.0"
  port = 30303
  bulk-sidecar = true
  bulk-port = 30304
  nodiscover = true
  maxpeers = 10
  maxpendpeers = 10
  nat = "extip:172.29.0.3"
  nodekeyhex = "6c3699283bda56ad74f6b855546325b68d482e983852a7a17dca9a3f7f0b6d65"
  [p2p.discovery]
    v4disc = false
    v5disc = false
    bootnodes = []
    dns = []

[jsonrpc]
  [jsonrpc.http]
    enabled = true
    host = "0.0.0.0"
    port = 8545
    api = ["eth", "net", "web3", "admin"]
    vhosts = ["*"]
    corsdomain = ["*"]

[heimdall]
  "bor.without" = true

[miner]
  mine = false

[witness]
  enable = true

[telemetry]
  metrics = true
