// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	clerk "github.com/ethereum/go-ethereum/consensus/bor/clerk"
	heimdall "github.com/ethereum/go-ethereum/consensus/bor/heimdall"
	mock "github.com/stretchr/testify/mock"
)

// IHeimdallClient is an autogenerated mock type for the IHeimdallClient type
type IHeimdallClient struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *IHeimdallClient) Close() {
	_m.Called()
}

// Fetch provides a mock function with given fields: path, query
func (_m *IHeimdallClient) Fetch(path string, query string) (*heimdall.ResponseWithHeight, error) {
	ret := _m.Called(path, query)

	var r0 *heimdall.ResponseWithHeight
	if rf, ok := ret.Get(0).(func(string, string) *heimdall.ResponseWithHeight); ok {
		r0 = rf(path, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*heimdall.ResponseWithHeight)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(path, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchStateSyncEvents provides a mock function with given fields: fromID, to
func (_m *IHeimdallClient) FetchStateSyncEvents(fromID uint64, to int64) ([]*clerk.EventRecordWithTime, error) {
	ret := _m.Called(fromID, to)

	var r0 []*clerk.EventRecordWithTime
	if rf, ok := ret.Get(0).(func(uint64, int64) []*clerk.EventRecordWithTime); ok {
		r0 = rf(fromID, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*clerk.EventRecordWithTime)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64, int64) error); ok {
		r1 = rf(fromID, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchWithRetry provides a mock function with given fields: path, query
func (_m *IHeimdallClient) FetchWithRetry(path string, query string) (*heimdall.ResponseWithHeight, error) {
	ret := _m.Called(path, query)

	var r0 *heimdall.ResponseWithHeight
	if rf, ok := ret.Get(0).(func(string, string) *heimdall.ResponseWithHeight); ok {
		r0 = rf(path, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*heimdall.ResponseWithHeight)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(path, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
